apiVersion: v1
kind: Secret
metadata:
  name: dispatcher-secret
  labels:
    app: dispatcher
    chart: {{ template "portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{ if .Values.dispatcher.additionalSecret }}
{{- range $key, $val := .Values.dispatcher.additionalSecret }}
  {{ $key }}: {{ $val | toString | b64enc }}
{{- end }}
{{ end }}
